on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    name: Python 3.9 
    env:
      PREPARED_STATEMENTS: true
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Run tests
      run: |
        docker compose version

        docker compose --project-name django-multitenant up -d || { docker compose logs && false ; }
        docker compose -f ./single-node-docker-compose.yml --project-name django-multitenant up -d
        pip install tox
        tox